// src/views/Stocks.vue
<template>
  <div class="content">
    <header>
      <AutoComplete />
    </header>
    <div class="table-responsive">
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th v-for="(val, key) in columns" :key="key">{{ key }}</th>
          </tr>
        </thead>
        <tbody id="sortable">
          <tr
            v-for="stock in stocks"
            :key="stock.index + stock.code"
            @click="gotoStock(stock)"
          >
            <td
              v-for="(val, key) in columns"
              :key="key"
              :style="addColor(stock, val)"
            >
              {{ stock[val] }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import AutoComplete from "@/components/AutoComplete.vue";
import Sortable from "sortablejs";
import { checkTime, post } from "@/misc.js";
import Cookies from "js-cookie";

const refresh = Cookies.get("Refresh") ? Cookies.get("Refresh") : 3;

export default {
  name: "Stocks",
  components: { AutoComplete },
  data() {
    return {
      columns: {
        指数: "index",
        代码: "code",
        名称: "name",
        最新: "now",
        涨跌: "change",
        涨幅: "percent",
        最高: "high",
        最低: "low",
        开盘: "open",
        昨收: "last",
      },
      stocks: [],
      sortable: "",
      refresh: Number(refresh) + 1,
      autoUpdate: "",
      fetching: "",
    };
  },
  created() {
    this.start();
  },
  mounted() {
    document.title = "My Stocks";
    this.sortable = new Sortable(document.querySelector("#sortable"), {
      animation: 150,
      delay: 500,
      swapThreshold: 0.5,
      onStart: () => this.stop(),
      onEnd: () => this.start(),
      onUpdate: this.onUpdate,
    });
  },
  beforeUnmount() {
    this.stop();
    this.sortable.destroy();
  },
  methods: {
    start() {
      this.load(true);
      this.autoUpdate = setInterval(this.load, this.refresh * 1000);
    },
    stop() {
      this.fetching.abort();
      clearInterval(this.autoUpdate);
    },
    async load(force) {
      if (checkTime() || force) {
        this.fetching = new AbortController();
        const resp = await fetch("/mystocks", { signal: this.fetching.signal });
        this.stocks = await resp.json();
      }
    },
    onUpdate(evt) {
      post("/reorder", {
        old: `${this.stocks[evt.oldIndex].index} ${
          this.stocks[evt.oldIndex].code
        }`,
        new: `${this.stocks[evt.newIndex].index} ${
          this.stocks[evt.newIndex].code
        }`,
      });
    },
  },
};
</script>

<style scoped>
.table-responsive {
  height: calc(100% - 54px);
  padding: 0px 30px;
  cursor: default;
}

th {
  position: sticky;
  top: 0;
  border-top: 0 !important;
  border-bottom: 0 !important;
  background-color: white;
}

.sortable-ghost {
  opacity: 0;
}
</style>

// src/components/Stocks.svelte
<script lang="ts">
  import Sortable from "sortablejs";
  import { onMount } from "svelte";
  import AutoComplete from "./AutoComplete.svelte";
  import { checkTime, post, addColor } from "../misc";
  import { current, component, refresh } from "../stores";
  import type { Stock } from "../stores";

  const columns = {
    指数: "index",
    代码: "code",
    名称: "name",
    最新: "now",
    涨跌: "change",
    涨幅: "percent",
    最高: "high",
    最低: "low",
    开盘: "open",
    昨收: "last",
  } as { [key: string]: keyof Stock };

  let stocks: Stock[] = [];
  let autoUpdate: number;
  let fetching: AbortController;

  const start = async () => {
    await load(true);
    autoUpdate = setInterval(load, $refresh * 1000);
  };

  const stop = () => {
    fetching.abort();
    clearInterval(autoUpdate);
  };

  const load = async (force?: boolean) => {
    if (checkTime() || force) {
      fetching = new AbortController();
      const resp = await fetch("/mystocks", { signal: fetching.signal });
      stocks = await resp.json();
    }
  };

  const goto = (stock: Stock) => {
    $current = stock;
    $component = "stock";
  };

  const onUpdate = async (evt: Sortable.SortableEvent) => {
    await post("/reorder", {
      old: `${stocks[evt.oldIndex as number].index} ${
        stocks[evt.oldIndex as number].code
      }`,
      new: `${stocks[evt.newIndex as number].index} ${
        stocks[evt.newIndex as number].code
      }`,
    });
  };

  onMount(() => {
    start();
    const sortable = new Sortable(
      document.querySelector("#sortable") as HTMLElement,
      {
        animation: 150,
        delay: 500,
        swapThreshold: 0.5,
        onStart: stop,
        onEnd: start,
        onUpdate,
      }
    );
    return () => {
      stop();
      sortable.destroy();
    };
  });
</script>

<svelte:head>
  <title>My Stocks</title>
</svelte:head>

<header>
  <AutoComplete />
</header>
<div class="table-responsive">
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        {#each Object.entries(columns) as [key, val] (key)}
          <th>{key}</th>
        {/each}
      </tr>
    </thead>
    <tbody id="sortable">
      {#each stocks as stock (stock.index + stock.code)}
        <tr on:click={() => goto(stock)}>
          {#each Object.entries(columns) as [key, val] (key)}
            <td style={addColor(stock, val)}>{stock[val]}</td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>

<style>
  .table-responsive {
    height: calc(100% - 54px);
    padding: 0px 30px;
    cursor: default;
  }

  th {
    position: sticky;
    top: 0;
    border-top: 0 !important;
    border-bottom: 0 !important;
    background-color: white;
  }

  :global(.sortable-ghost) {
    opacity: 0;
  }
</style>
